"""A native launcher — a double-clickable icon, not an application framework.

The workbench is already a local web app that `onpar ui` serves. What is
missing for anyone who does not live in a terminal is the step before that:
opening one.

## Why not Tauri, Electron, or a real shell

A desktop framework would add a Rust-plus-Node toolchain, platform SDKs, code
signing and notarisation — a substantial permanent cost — to produce a window
around a page the browser already renders correctly. It would also mean shipping
a second browser engine to display a page whose only requirement is a browser.

The 90%-of-the-value version is an OS-native *launcher*: a `.app` on macOS and a
`.desktop` entry on Linux, both of which start the existing server and open the
existing UI. Nothing new to maintain, no new failure modes, and it uninstalls by
deleting a folder.

The 10% given up, stated honestly: no custom menu bar, no native file dialogs, no
offline packaging of Python itself. If those are ever wanted, the thing to build
is a real shell — and this module should be deleted rather than grown into one.

## What it does not do

It does not install Python, bundle an interpreter, or auto-update. A launcher
that silently reinstalls its own runtime is a support burden wearing a
convenience.
"""

from __future__ import annotations

import contextlib
import os
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

__all__ = ["Launcher", "demo", "install", "launch_script", "plist"]

APP_NAME = "onpar"
DEFAULT_PORT = 7171


@dataclass(frozen=True, slots=True)
class Launcher:
    """Where a launcher was installed, and how to remove it."""

    path: Path
    kind: str
    #: The exact command a user runs to undo this. Printed on install, because a
    #: thing that installs itself into your Applications folder should say how
    #: to get rid of it before you find out you need to know.
    uninstall: str


def launch_script(python: str, port: int = DEFAULT_PORT) -> str:
    """The shell script both platforms run.

    Reuses `onpar ui`, which already starts the server and opens a browser.
    Duplicating that here would be a second implementation of the one thing the
    launcher exists to invoke.
    """
    return (
        "#!/usr/bin/env bash\n"
        "# Generated by onpar. Starts the local workbench and opens it.\n"
        "# Nothing here talks to the network: the UI is served from 127.0.0.1.\n"
        "set -euo pipefail\n\n"
        f'PY="{python}"\n'
        f"PORT={port}\n\n"
        "# If something is already listening, open that rather than starting a\n"
        "# second server and failing on a port clash — double-clicking twice is\n"
        "# a thing people do.\n"
        'URL="http://127.0.0.1:$PORT/"\n'
        'if command -v curl >/dev/null && curl -fsS "$URL" -o /dev/null 2>&1; then\n'
        '  open "$URL" 2>/dev/null || xdg-open "$URL" 2>/dev/null || true\n'
        "  exit 0\n"
        "fi\n\n"
        'exec "$PY" -m onpar.cli ui --port "$PORT"\n'
    )


def plist(exec_name: str) -> str:
    """The macOS `Info.plist` for a minimal .app bundle.

    `LSBackgroundOnly` is deliberately absent: the process must own a Dock icon
    so it can be quit the way every other app is quit. A background-only app
    that serves a web page is a process users cannot find to stop.
    """
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0">\n<dict>\n'
        f"  <key>CFBundleName</key><string>{APP_NAME}</string>\n"
        f"  <key>CFBundleDisplayName</key><string>{APP_NAME}</string>\n"
        f"  <key>CFBundleIdentifier</key><string>dev.onpar.launcher</string>\n"
        f"  <key>CFBundleExecutable</key><string>{exec_name}</string>\n"
        "  <key>CFBundleVersion</key><string>0.1.0</string>\n"
        "  <key>CFBundlePackageType</key><string>APPL</string>\n"
        "  <key>NSHighResolutionCapable</key><true/>\n"
        "</dict>\n</plist>\n"
    )


def desktop_entry(exec_path: Path) -> str:
    """A freedesktop `.desktop` entry."""
    return (
        "[Desktop Entry]\n"
        "Type=Application\n"
        f"Name={APP_NAME}\n"
        "Comment=Run open models properly on your own hardware\n"
        f"Exec={exec_path}\n"
        "Terminal=false\n"
        "Categories=Development;Science;\n"
        "Keywords=llm;inference;benchmark;\n"
    )


def _macos(root: Path, python: str, port: int) -> Launcher:
    """A .app bundle — three files and a directory layout, no toolchain."""
    app = root / f"{APP_NAME}.app"
    macos = app / "Contents" / "MacOS"
    macos.mkdir(parents=True, exist_ok=True)

    exe = macos / APP_NAME
    exe.write_text(launch_script(python, port))
    exe.chmod(0o755)
    (app / "Contents" / "Info.plist").write_text(plist(APP_NAME))
    return Launcher(app, "macos", f"rm -rf {shlex.quote(str(app))}")


def _linux(root: Path, python: str, port: int, bin_dir: Path | None = None) -> Launcher:
    """A .desktop entry plus the script it points at.

    Two directories, because freedesktop separates them: the entry belongs in
    `~/.local/share/applications` and the executable on `PATH`. That split is
    correct — and `bin_dir` was hard-coded to the real home, so a caller who
    passed `target=` had the entry land where they asked and the *script* land
    in `~/.local/bin` regardless. A test installing to a temporary directory
    wrote to the user's home; there is no test for this function, which is why
    nobody noticed.
    """
    bin_dir = bin_dir or Path.home() / ".local" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    exe = bin_dir / f"{APP_NAME}-ui"
    exe.write_text(launch_script(python, port))
    exe.chmod(0o755)

    root.mkdir(parents=True, exist_ok=True)
    entry = root / f"{APP_NAME}.desktop"
    entry.write_text(desktop_entry(exe))
    return Launcher(entry, "linux", f"rm -f {shlex.quote(str(entry))} {shlex.quote(str(exe))}")


def install(
    target: Path | None = None,
    python: str | None = None,
    port: int = DEFAULT_PORT,
    bin_dir: Path | None = None,
) -> Launcher:
    """Install a launcher for this platform.

    Args:
        target: where to put it. Defaults to `~/Applications` on macOS and
            `~/.local/share/applications` on Linux — the per-user locations,
            never the system ones, because a tool should not need root to add
            an icon.
        python: interpreter to launch with. Defaults to the one running this,
            so a virtualenv install keeps working after the shell is closed.
        port: port for the workbench.
        bin_dir: Linux only — where the launch script goes. Defaults to
            `~/.local/bin`, which is the freedesktop convention and the reason
            it is a separate argument rather than derived from `target`. Pass
            it to keep an install self-contained.

    Raises:
        RuntimeError: on an unsupported platform, naming it rather than
            producing a launcher that cannot work.
    """
    python = python or sys.executable
    if sys.platform == "darwin":
        return _macos(target or Path.home() / "Applications", python, port)
    if sys.platform.startswith("linux"):
        return _linux(
            target or Path.home() / ".local" / "share" / "applications", python, port, bin_dir
        )
    raise RuntimeError(
        f"no launcher for {sys.platform}. `onpar ui` works everywhere — this "
        f"only adds the icon, and adding one on this platform is not implemented."
    )


def reveal(path: Path) -> bool:
    """Show the installed launcher in the file manager. Best effort."""
    for cmd in (["open", "-R", str(path)], ["xdg-open", str(path.parent)]):
        if shutil.which(cmd[0]):
            # Failing to open a file manager is not worth an error path; the
            # launcher is already installed and its location was printed.
            with contextlib.suppress(OSError, subprocess.SubprocessError):
                subprocess.run(cmd, check=False, timeout=5)
                return True
    return False


def demo() -> None:
    """Self-check. Run with `python -m onpar.desktop`."""
    import tempfile

    script = launch_script("/usr/bin/python3", 7171)
    # It must reuse `onpar ui` rather than reimplement serving.
    assert "onpar.cli ui" in script
    assert "--port" in script
    # Double-clicking twice must not fail on a port clash.
    assert "already listening" in script or "127.0.0.1:$PORT" in script
    assert "exit 0" in script
    # Nothing may phone home; the UI is loopback-only.
    assert "127.0.0.1" in script and "0.0.0.0" not in script

    p = plist("onpar")
    assert "CFBundleExecutable" in p and "onpar" in p
    # A background-only app serving a web page cannot be quit by normal means.
    assert "LSBackgroundOnly" not in p

    with tempfile.TemporaryDirectory() as d:
        root = Path(d)
        if sys.platform == "darwin":
            lz = _macos(root, "/usr/bin/python3", 7171)
            exe = lz.path / "Contents" / "MacOS" / APP_NAME
            assert exe.exists() and os.access(exe, os.X_OK), "the bundle must be executable"
            assert (lz.path / "Contents" / "Info.plist").exists()
            assert lz.kind == "macos"
        else:
            # Exercise the generator without writing to a real ~/.local.
            entry = desktop_entry(Path("/usr/local/bin/onpar-ui"))
            assert "Type=Application" in entry and "Terminal=false" in entry

        # Uninstall must be a command the user can read and run.
        made = _macos(root, "/usr/bin/python3", 7171)
        assert made.uninstall.startswith("rm -rf ") and str(root) in made.uninstall

    print("desktop: ok")


if __name__ == "__main__":
    demo()
